fkunn1326/openpose-editor

javascript/main.js

When moving width / height sliders on txt2img after using the "Detect to image" feature on the extension, the page gets laggier the more you use the sliders.
This should also fix #4 
I moved the canvas event listeners to `initCanvas()` instead of `setPose()`.
The `MutationObserver` named `json_observer` makes a call to `setPose()`, which in turn adds new event listeners to the canvas, **everytime** the method gets called. Moving this logic to `initCanvas()` prevents this issue.
I also added some logic to check if the extension tab is in focus when calling the `MutationObserver` to further optimize the UI when not using the extension.

fix: prevent canvas event listeners duplication

---

README.en.md
README.md

I tried to detect poses from images, but an error occurred, so I added a note about the countermeasure.

Add information about certifi error

---

.github/workflows/typos.yml
_typos.toml
scripts/openpose/body.py
scripts/openpose/util.py

You can get the binary from the [typos release page](https://github.com/crate-ci/typos/releases) to use locally.

Fix typos and add typo checker to CI

---

scripts/openpose/body.py

the commit to fix typos https://github.com/fkunn1326/openpose-editor/pull/27 actually introduces typos instead. "threthold" is not a word. I made a comment on said pull request but it was merged anyways.

fix typos introduced by fixing typos commit

---

javascript/main.js
scripts/main.py

Fix https://github.com/fkunn1326/openpose-editor/issues/39

Add support for Multi ControlNet

---

javascript/main.js

Fix ffmpeg error

---

scripts/main.py

ControlNet has `body_pose_model.pth` in `models/openpose`. This'll use that instead of downloading it again.

Update model path

---

javascript/main.js
scripts/main.py

Updated `Send to...` to work with multi-ControlNet tabs. 
Fixes #68

Fix multi-ControlNet

---

scripts/main.py

Successfully installed after removing unnecessary parentheses according to grammar errors.

Remove unnecessary parentheses.

---

scripts/main.py

fix main.py invalid syntax error

fix main.py invalid syntax error

---

scripts/main.py

https://docs.python.org/3.10/library/functions.html#getattr

Simplify control_net_max_models_num

---

javascript/main.js
scripts/main.py
style.css

Adds a preset menu. Presets are stored in `presets.json`
Closes #50

Preset support

---

javascript/main.js

Fix sliders not updating when dropping background

---

javascript/main.js

I noticed that auto1111 [already has a function](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2/script.js#L24-L26) to do exactly what this event listener did.

Replace DOMContentLoaded listener with onUiLoaded()

---

javascript/main.js
scripts/main.py

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8752
`gr.UploadButton()` doesn't seem to return a data URL anymore, so that all had to be fixed.
Updated `Detect from Image` to use `then()` instead of a mutation observer.

Update for gradio 3.23

---

javascript/main.js
scripts/main.py

Fix compatibility with Gradio 3.16

---

javascript/main.js

Seems to be causing problems. No need to replicate it,
Fixes #97
Fixes #96
Fixes https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8980

Remove gradioApp() function.

---

javascript/main.js

The original _detectImage_ function may result in confusing output when not all keypoints are detected, like the following picture:
Such confusing output was reported as a **bug** in [issue #115](https://github.com/fkunn1326/openpose-editor/issues/115)
Here is how this problem was caused: in the original _detectImage_ function, keypoints that were not detected will be assigned a random coordinate, as follows:
```
if (Number.isInteger(subset[i]) && subset[i] >= 0){
li.push(candidate[subset[i]])
}else{
const ra_width = Math.floor(Math.random() * openpose_editor_canvas.width)
const ra_height = Math.floor(Math.random() * openpose_editor_canvas.height)
li.push([ra_width, ra_height])
}
```
As a result, we see undetected keypoints scattered randomly on the image, and the detected pose is …

improve detectImage

---

javascript/main.js

this is a quick hack to support multi-person keypoints.

support multi person keypoints

---

javascript/main.js

see also Ning Haojian's improved detectImage() method suggested at PR #116 0cfb1353ad
json used by the openpose editor
~~~json
{
"width": 640,
"height": 640,
"keypoints": [
...
}
~~~
json used by the latest controlnet
~~~json
{
"people": [
{
"pose_keypoints_2d": [
...
],
"canvas_height": 640,
"canvas_width": 640
}
~~~

support jsonLoad for latest ControlNet
